name: Static Code Analysis

on:
  pull_request:
  push:
    branches:
      - develop
      - main
      - 'release/**'
      - 'feature/**'
      - 'fix/**'

env:
  PHP_VERSION: '8.0'
  COMPOSER_VERSION: '2.2'
  NODE_VERSION: 14
  PROJECT_PATH: './'

jobs:
  check:
    name: Setup & Check

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ env.PROJECT_PATH }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup PHP Environment
      uses: shivammathur/setup-php@v2
      # https://github.com/marketplace/actions/setup-php-action
      with:
        php-version: "${{ env.PHP_VERSION }}"
        tools: "composer:${{ env.COMPOSER_VERSION }}"

    - name: Environment Check
      run: php -v && composer --version

    - name: Cache Composer dependencies
      uses: actions/cache@v2
      env:
        composer-cache-name: cache-vendor
      with:
        path: ~/vendor
        key: ${{ runner.os }}-build-${{ env.composer-cache-name }}-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.composer-cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Install Composer Dependencies
      run: composer install

    - name: Perform Static Analysis
      run: composer run-script analyze
